#!/bin/bash
#SBATCH -N 1
#SBATCH -p GPU-shared
#SBATCH --ntasks-per-node 2
#SBATCH --gres=gpu:p100:1
#SBATCH -t 10:00:00

module load anaconda/4.2.0-3.5.2
module load cuda/8.0
source activate nn

set -x
set -u
set -e
python multiple_style.py
