#!/bin/bash
#SBATCH --job-name="nn-new"
#SBATCH --output="ever12-masked-novw.out"
#SBATCH --nodes=1
#SBATCH --partition=GPU-shared
#SBATCH --ntasks-per-node 1
#SBATCH --gres=gpu:p100:1
#SBARCH --export=ALL
#SBATCH -t 10:00:00

set -x
set -u
set -e
python -i mask_transfer.py --total_variation_weight 0  --content_weight 0 --style_weight 1 --rescale_image True --num_iter 1500 --style_masks everfilter/mask/12.jpg Tuebingen_Neckarfront.jpg everfilter/12.jpg everfilter12-masked-novw

