#!/bin/bash
#SBATCH --job-name="nn-new"
#SBATCH --output="ever6-7-9-15-novw-masked.out"
#SBATCH --nodes=1
#SBATCH --partition=GPU-shared
#SBATCH --ntasks-per-node 1
#SBATCH --gres=gpu:p100:1
#SBARCH --export=ALL
#SBATCH -t 35:00:00

set -x
set -u
set -e
python -i mask_transfer.py --total_variation_weight 0  --content_weight 0 --style_weight 1 --rescale_image True --num_iter 1500 --style_masks everfilter/mask/6.jpg everfilter/mask/7.jpg everfilter/mask/9.jpg everfilter/mask/15.jpg  Tuebingen_Neckarfront.jpg everfilter/6.jpg everfilter/7.jpg everfilter/9.jpg everfilter/15.jpg everfilter6-7-9-15-masked-novw

